"""intelligence layer: documents chunks verification_requests

Revision ID: 1d8e57f7982e
Revises: b963e710a051
Create Date: 2026-09-01 23:20:22.880447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8e57f7982e'
down_revision: Union[str, None] = 'b963e710a051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Enum('html', 'pdf', 'text', name='document_type_enum', native_enum=False), server_default='html', nullable=False),
    sa.Column('language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at_doc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_documents_content_hash', 'documents', ['content_hash'], unique=False)
    op.create_index('ix_documents_source', 'documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_index('ix_documents_url', 'documents', ['url'], unique=False)
    op.create_table('verification_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('input_type', sa.Enum('text', 'image', 'voice', name='vr_input_type_enum', native_enum=False), nullable=False),
    sa.Column('original_input', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='vr_status_enum', native_enum=False), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_requests_user_id'), 'verification_requests', ['user_id'], unique=False)
    op.create_index('ix_vr_status', 'verification_requests', ['status'], unique=False)
    op.create_index('ix_vr_user', 'verification_requests', ['user_id'], unique=False)
    op.create_table('evidence_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_chunks_document', 'evidence_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_evidence_chunks_document_id'), 'evidence_chunks', ['document_id'], unique=False)
    op.create_index('ix_evidence_chunks_document_index', 'evidence_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_table('claim_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('support_type', sa.String(length=20), nullable=True),
    sa.Column('retrieval_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['evidence_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'chunk_id', name='uq_claim_chunk')
    )
    op.create_index('ix_claim_evidence_chunk', 'claim_evidence', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_claim_evidence_chunk_id'), 'claim_evidence', ['chunk_id'], unique=False)
    op.create_index('ix_claim_evidence_claim', 'claim_evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_evidence_claim_id'), 'claim_evidence', ['claim_id'], unique=False)
    # SQLite needs batch mode for altering column nullability + FK
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_request_id', sa.Uuid(), nullable=True))
        batch_op.alter_column('submission_id',
                   existing_type=sa.CHAR(length=32),
                   nullable=True)
        batch_op.create_index('ix_claims_verification_request_id', ['verification_request_id'], unique=False)
        batch_op.create_foreign_key('fk_claims_verification_request_id', 'verification_requests', ['verification_request_id'], ['id'], ondelete='CASCADE')
    op.add_column('sources', sa.Column('authority_level', sa.Integer(), server_default='3', nullable=False))
    op.add_column('sources', sa.Column('country', sa.String(length=10), server_default='IN', nullable=False))
    op.add_column('sources', sa.Column('language', sa.String(length=10), server_default='en', nullable=False))
    op.add_column('sources', sa.Column('is_trusted', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'is_trusted')
    op.drop_column('sources', 'language')
    op.drop_column('sources', 'country')
    op.drop_column('sources', 'authority_level')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_constraint('fk_claims_verification_request_id', type_='foreignkey')
        batch_op.drop_index('ix_claims_verification_request_id')
        batch_op.alter_column('submission_id',
                   existing_type=sa.CHAR(length=32),
                   nullable=False)
        batch_op.drop_column('verification_request_id')
    op.drop_index(op.f('ix_claim_evidence_claim_id'), table_name='claim_evidence')
    op.drop_index('ix_claim_evidence_claim', table_name='claim_evidence')
    op.drop_index(op.f('ix_claim_evidence_chunk_id'), table_name='claim_evidence')
    op.drop_index('ix_claim_evidence_chunk', table_name='claim_evidence')
    op.drop_table('claim_evidence')
    op.drop_index('ix_evidence_chunks_document_index', table_name='evidence_chunks')
    op.drop_index(op.f('ix_evidence_chunks_document_id'), table_name='evidence_chunks')
    op.drop_index('ix_evidence_chunks_document', table_name='evidence_chunks')
    op.drop_table('evidence_chunks')
    op.drop_index('ix_vr_user', table_name='verification_requests')
    op.drop_index('ix_vr_status', table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_user_id'), table_name='verification_requests')
    op.drop_table('verification_requests')
    op.drop_index('ix_documents_url', table_name='documents')
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index('ix_documents_source', table_name='documents')
    op.drop_index('ix_documents_content_hash', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
