"""initial schema

Revision ID: b963e710a051
Revises: 
Create Date: 2026-09-01 22:49:52.219161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b963e710a051'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=True),
    sa.Column('source_type', sa.Enum('government', 'regulator', 'international_organization', 'research', 'news', 'other', name='source_type_enum', native_enum=False), server_default='other', nullable=False),
    sa.Column('trust_level', sa.Integer(), server_default='3', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('input_type', sa.Enum('text', 'image', 'voice', name='input_type_enum', native_enum=False), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='submission_status_enum', native_enum=False), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submissions_status', 'submissions', ['status'], unique=False)
    op.create_index('ix_submissions_user_created', 'submissions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('normalized_claim', sa.Text(), nullable=True),
    sa.Column('claim_type', sa.Enum('factual', 'prediction', 'opinion', 'other', name='claim_type_enum', native_enum=False), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'verified', 'contradicted', 'uncertain', name='claim_status_enum', native_enum=False), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claims_status', 'claims', ['status'], unique=False)
    op.create_index('ix_claims_submission', 'claims', ['submission_id'], unique=False)
    op.create_index(op.f('ix_claims_submission_id'), 'claims', ['submission_id'], unique=False)
    op.create_index('ix_claims_submission_status', 'claims', ['submission_id', 'status'], unique=False)
    op.create_table('extracted_content',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.Enum('ocr', 'transcript', 'normalized_text', name='content_type_enum', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('extraction_method', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extracted_content_submission', 'extracted_content', ['submission_id'], unique=False)
    op.create_index(op.f('ix_extracted_content_submission_id'), 'extracted_content', ['submission_id'], unique=False)
    op.create_table('input_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_input_files_submission', 'input_files', ['submission_id'], unique=False)
    op.create_index(op.f('ix_input_files_submission_id'), 'input_files', ['submission_id'], unique=False)
    op.create_table('claim_entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_text', sa.String(length=500), nullable=False),
    sa.Column('normalized_value', sa.String(length=500), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claim_entities_claim', 'claim_entities', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_entities_claim_id'), 'claim_entities', ['claim_id'], unique=False)
    op.create_index('ix_claim_entities_type', 'claim_entities', ['entity_type'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('evidence_type', sa.Enum('supporting', 'contradicting', 'contextual', name='evidence_type_enum', native_enum=False), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_claim', 'evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evidence_claim_id'), 'evidence', ['claim_id'], unique=False)
    op.create_index('ix_evidence_claim_source', 'evidence', ['claim_id', 'source_id'], unique=False)
    op.create_index('ix_evidence_source', 'evidence', ['source_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_id'), 'evidence', ['source_id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('result', sa.Enum('verified', 'contradicted', 'uncertain', name='verification_result_enum', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verifications_claim', 'verifications', ['claim_id'], unique=False)
    op.create_index(op.f('ix_verifications_claim_id'), 'verifications', ['claim_id'], unique=False)
    op.create_index('ix_verifications_result', 'verifications', ['result'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.Enum('helpful', 'not_helpful', 'incorrect', 'missing_context', 'other', name='feedback_type_enum', native_enum=False), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_user', 'feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_index('ix_feedback_verification', 'feedback', ['verification_id'], unique=False)
    op.create_index(op.f('ix_feedback_verification_id'), 'feedback', ['verification_id'], unique=False)
    op.create_table('verification_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='verification_run_status_enum', native_enum=False), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('pipeline_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_runs_status', 'verification_runs', ['status'], unique=False)
    op.create_index('ix_verification_runs_verification', 'verification_runs', ['verification_id'], unique=False)
    op.create_index(op.f('ix_verification_runs_verification_id'), 'verification_runs', ['verification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_runs_verification_id'), table_name='verification_runs')
    op.drop_index('ix_verification_runs_verification', table_name='verification_runs')
    op.drop_index('ix_verification_runs_status', table_name='verification_runs')
    op.drop_table('verification_runs')
    op.drop_index(op.f('ix_feedback_verification_id'), table_name='feedback')
    op.drop_index('ix_feedback_verification', table_name='feedback')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index('ix_feedback_user', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_verifications_result', table_name='verifications')
    op.drop_index(op.f('ix_verifications_claim_id'), table_name='verifications')
    op.drop_index('ix_verifications_claim', table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_evidence_source_id'), table_name='evidence')
    op.drop_index('ix_evidence_source', table_name='evidence')
    op.drop_index('ix_evidence_claim_source', table_name='evidence')
    op.drop_index(op.f('ix_evidence_claim_id'), table_name='evidence')
    op.drop_index('ix_evidence_claim', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_claim_entities_type', table_name='claim_entities')
    op.drop_index(op.f('ix_claim_entities_claim_id'), table_name='claim_entities')
    op.drop_index('ix_claim_entities_claim', table_name='claim_entities')
    op.drop_table('claim_entities')
    op.drop_index(op.f('ix_input_files_submission_id'), table_name='input_files')
    op.drop_index('ix_input_files_submission', table_name='input_files')
    op.drop_table('input_files')
    op.drop_index(op.f('ix_extracted_content_submission_id'), table_name='extracted_content')
    op.drop_index('ix_extracted_content_submission', table_name='extracted_content')
    op.drop_table('extracted_content')
    op.drop_index('ix_claims_submission_status', table_name='claims')
    op.drop_index(op.f('ix_claims_submission_id'), table_name='claims')
    op.drop_index('ix_claims_submission', table_name='claims')
    op.drop_index('ix_claims_status', table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index('ix_submissions_user_created', table_name='submissions')
    op.drop_index('ix_submissions_status', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sources')
    # ### end Alembic commands ###
